# Generated by Django 3.0.5 on 2020-05-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codepostal', models.CharField(blank=True, max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=60, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=60, null=True)),
                ('name_en', models.CharField(blank=True, max_length=60, null=True)),
                ('latitude_south', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('latitude_north', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude_west', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude_east', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('latitude_southa', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('latitude_northa', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude_westa', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude_easta', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('category_1', models.SmallIntegerField(blank=True, null=True)),
                ('category_2', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrip', models.TextField(blank=True)),
                ('extrainfo', models.CharField(blank=True, max_length=250, null=True)),
                ('payactive', models.NullBooleanField()),
                ('active', models.NullBooleanField()),
                ('dateexp', models.DateTimeField(blank=True, null=True)),
                ('starthostdate', models.DateTimeField(blank=True, null=True)),
                ('endhostdate', models.DateTimeField(blank=True, null=True)),
                ('hosted', models.NullBooleanField()),
                ('hostactive', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'permissions': (('manage_course', 'Manage course'),),
            },
        ),
        migrations.CreateModel(
            name='CourseAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.CreateModel(
            name='CourseArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=30, null=True)),
                ('name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
        migrations.CreateModel(
            name='CourseLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=30, null=True)),
                ('name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('tag', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=30, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=30, null=True)),
                ('name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='CourseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.SmallIntegerField()),
                ('number_sessions', models.SmallIntegerField(blank=True, null=True)),
                ('coursestartdate', models.DateTimeField(blank=True, null=True)),
                ('courseenddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='CourseLocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_fr', models.CharField(max_length=25, null=True)),
                ('name_ar', models.CharField(max_length=25, null=True)),
                ('name_en', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('iso_code', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='HandoutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(upload_to='handouts/%Y-%m-%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.HandoutSection')),
            ],
            options={
                'verbose_name': 'Handout',
                'verbose_name_plural': 'Handout',
                'permissions': (('manage_handout', 'Manage handout'),),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollment',
                'permissions': (('manage_enrollment', 'Manage enrollment'),),
            },
        ),
    ]
