# Generated by Django 3.0.5 on 2020-05-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Currency'),
        ),
        migrations.AddField(
            model_name='courselocation',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.CourseLocationType'),
        ),
        migrations.AddField(
            model_name='course',
            name='age',
            field=models.ManyToManyField(to='courses.CourseAge'),
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ManyToManyField(to='courses.CourseArea'),
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.City'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.CourseDuration'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(to='courses.CourseLanguage'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseLevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
    ]
