# Generated by Django 3.0.5 on 2020-06-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('courses', '0002_auto_20200528_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='center_pics/%Y-%m-%d/')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor')),
            ],
            options={
                'verbose_name': 'Center',
                'verbose_name_plural': 'Centers',
                'permissions': (('manage_center', 'Manage center'),),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Center'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.NullBooleanField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Center')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Professor')),
            ],
            options={
                'verbose_name': 'JoinRequest',
                'verbose_name_plural': 'JoinRequest',
                'permissions': (('manage_join_request', 'Manage join request'),),
                'unique_together': {('center', 'professor')},
            },
        ),
    ]
