# Generated by Django 3.0.5 on 2020-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200604_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'permissions': (('manage_join_request', 'Manage join request'),), 'verbose_name': 'Join request', 'verbose_name_plural': 'Join requests'},
        ),
        migrations.AlterField(
            model_name='center',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
